// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ourshop.it.domain;

import com.ourshop.it.domain.Inventory;
import com.ourshop.it.domain.InventoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect InventoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InventoryDataOnDemand: @Component;
    
    private Random InventoryDataOnDemand.rnd = new SecureRandom();
    
    private List<Inventory> InventoryDataOnDemand.data;
    
    public Inventory InventoryDataOnDemand.getNewTransientInventory(int index) {
        Inventory obj = new Inventory();
        setItemCost(obj, index);
        setItemDescription(obj, index);
        setItemName(obj, index);
        return obj;
    }
    
    public void InventoryDataOnDemand.setItemCost(Inventory obj, int index) {
        Double itemCost = new Integer(index).doubleValue();
        obj.setItemCost(itemCost);
    }
    
    public void InventoryDataOnDemand.setItemDescription(Inventory obj, int index) {
        String itemDescription = "itemDescription_" + index;
        obj.setItemDescription(itemDescription);
    }
    
    public void InventoryDataOnDemand.setItemName(Inventory obj, int index) {
        String itemName = "itemName_" + index;
        obj.setItemName(itemName);
    }
    
    public Inventory InventoryDataOnDemand.getSpecificInventory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Inventory obj = data.get(index);
        Long id = obj.getId();
        return Inventory.findInventory(id);
    }
    
    public Inventory InventoryDataOnDemand.getRandomInventory() {
        init();
        Inventory obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Inventory.findInventory(id);
    }
    
    public boolean InventoryDataOnDemand.modifyInventory(Inventory obj) {
        return false;
    }
    
    public void InventoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Inventory.findInventoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Inventory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Inventory>();
        for (int i = 0; i < 10; i++) {
            Inventory obj = getNewTransientInventory(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
