// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ourshop.it.domain;

import com.ourshop.it.domain.TransactionInventoryDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TransactionInventoryDataOnDemand_Roo_Configurable {
    
    declare @type: TransactionInventoryDataOnDemand: @Configurable;
    
}
