// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ourshop.it.domain;

import com.ourshop.it.domain.TransactionInventory;
import com.ourshop.it.domain.TransactionInventoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TransactionInventoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TransactionInventoryDataOnDemand: @Component;
    
    private Random TransactionInventoryDataOnDemand.rnd = new SecureRandom();
    
    private List<TransactionInventory> TransactionInventoryDataOnDemand.data;
    
    public TransactionInventory TransactionInventoryDataOnDemand.getNewTransientTransactionInventory(int index) {
        TransactionInventory obj = new TransactionInventory();
        setQuantity(obj, index);
        setRate(obj, index);
        return obj;
    }
    
    public void TransactionInventoryDataOnDemand.setQuantity(TransactionInventory obj, int index) {
        Double quantity = new Integer(index).doubleValue();
        obj.setQuantity(quantity);
    }
    
    public void TransactionInventoryDataOnDemand.setRate(TransactionInventory obj, int index) {
        Double rate = new Integer(index).doubleValue();
        obj.setRate(rate);
    }
    
    public TransactionInventory TransactionInventoryDataOnDemand.getSpecificTransactionInventory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TransactionInventory obj = data.get(index);
        Long id = obj.getId();
        return TransactionInventory.findTransactionInventory(id);
    }
    
    public TransactionInventory TransactionInventoryDataOnDemand.getRandomTransactionInventory() {
        init();
        TransactionInventory obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TransactionInventory.findTransactionInventory(id);
    }
    
    public boolean TransactionInventoryDataOnDemand.modifyTransactionInventory(TransactionInventory obj) {
        return false;
    }
    
    public void TransactionInventoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TransactionInventory.findTransactionInventoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TransactionInventory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TransactionInventory>();
        for (int i = 0; i < 10; i++) {
            TransactionInventory obj = getNewTransientTransactionInventory(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
