// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ourshop.it.domain;

import com.ourshop.it.domain.AccountDataOnDemand;
import com.ourshop.it.domain.PartyDataOnDemand;
import com.ourshop.it.domain.Transactions;
import com.ourshop.it.domain.TransactionsDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TransactionsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TransactionsDataOnDemand: @Component;
    
    private Random TransactionsDataOnDemand.rnd = new SecureRandom();
    
    private List<Transactions> TransactionsDataOnDemand.data;
    
    @Autowired
    AccountDataOnDemand TransactionsDataOnDemand.accountDataOnDemand;
    
    @Autowired
    PartyDataOnDemand TransactionsDataOnDemand.partyDataOnDemand;
    
    public Transactions TransactionsDataOnDemand.getNewTransientTransactions(int index) {
        Transactions obj = new Transactions();
        setAdvanceAmount(obj, index);
        setDescription(obj, index);
        setDiscountAmount(obj, index);
        setDueAmount(obj, index);
        setTotalAmount(obj, index);
        setTransactionDate(obj, index);
        setType(obj, index);
        return obj;
    }
    
    public void TransactionsDataOnDemand.setAdvanceAmount(Transactions obj, int index) {
        Double advanceAmount = new Integer(index).doubleValue();
        obj.setAdvanceAmount(advanceAmount);
    }
    
    public void TransactionsDataOnDemand.setDescription(Transactions obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void TransactionsDataOnDemand.setDiscountAmount(Transactions obj, int index) {
        Double discountAmount = new Integer(index).doubleValue();
        obj.setDiscountAmount(discountAmount);
    }
    
    public void TransactionsDataOnDemand.setDueAmount(Transactions obj, int index) {
        Double dueAmount = new Integer(index).doubleValue();
        obj.setDueAmount(dueAmount);
    }
    
    public void TransactionsDataOnDemand.setTotalAmount(Transactions obj, int index) {
        Double totalAmount = new Integer(index).doubleValue();
        obj.setTotalAmount(totalAmount);
    }
    
    public void TransactionsDataOnDemand.setTransactionDate(Transactions obj, int index) {
        Date transactionDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setTransactionDate(transactionDate);
    }
    
    public void TransactionsDataOnDemand.setType(Transactions obj, int index) {
        String type = "type_" + index;
        obj.setType(type);
    }
    
    public Transactions TransactionsDataOnDemand.getSpecificTransactions(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Transactions obj = data.get(index);
        Long id = obj.getId();
        return Transactions.findTransactions(id);
    }
    
    public Transactions TransactionsDataOnDemand.getRandomTransactions() {
        init();
        Transactions obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Transactions.findTransactions(id);
    }
    
    public boolean TransactionsDataOnDemand.modifyTransactions(Transactions obj) {
        return false;
    }
    
    public void TransactionsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Transactions.findTransactionsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Transactions' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Transactions>();
        for (int i = 0; i < 10; i++) {
            Transactions obj = getNewTransientTransactions(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
