---
spring:
  profiles: default
l7.gateway: 
  node1: http://somehost.one.com:8081
  node2: http://somehost.two.com:8081
  nodelb: https://somehost.com

server:
  port: 14325  
---
spring:
  profiles: sandbox

---
spring:
  profiles: prod

---
spring:
  profiles: test
