---
spring:
  profiles: default
l7.gateway: 
  node1: http://ssgosgdev02.isus.emc.com:8081
  node2: http://ssgosgdev03.isus.emc.com:8081
  nodelb: https://ssgosgdev.isus.emc.com

server:
  port: 14325  
---
spring:
  profiles: sandbox

---
spring:
  profiles: prod

---
spring:
  profiles: test
